# .goreleaser.yml
# Build customization
builds:
  - binary: metrics
    main: ./cmd/metrics-api/metrics-api.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  