# .goreleaser.yml
# Build customization
builds:
  # makefile currently relies on this name
  - binary: aerogear-app-metrics
    main: ./cmd/metrics-api/metrics-api.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  